name: build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          skip-go-installation: true

      - name: Build
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --snapshot --rm-dist
