name: goreleaser

on:
  push:
    tags:
      - v*

env:
  dockerpushrm_version: "1.7.0"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login Github Container Registry
        id: githubContainerRegistryLogin
        uses: docker/login-action@v2.1.0
        with:
          registry: "ghcr.io"
          username: "jkaflik"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          skip-go-installation: true

      - name: Create Release
        id: createRelease
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
